// Generated by CoffeeScript 1.8.0
(function() {
  chrome.runtime.onMessage.addListener(function(request, sender, sendResponse) {
    return chrome.tabs.query({
      currentWindow: true,
      active: true
    }, function(tabs) {
      return chrome.tabs.remove(tabs[0].id);
    });
  });

}).call(this);
